#$schema: 'https://www.schemastore.org/pnpm-workspace.json'

# installs any missing peer dependencies as dev dependencies
autoInstallPeers: true

# for pnpm, use flat node_modules
shamefullyHoist: true
